version: 0.2

phases:
  install:
    commands:
      - yum -y update
      - yum install -y openjdk-11-jdk
      - yum install -y maven
  pre_build:
    commands:
      - echo "Starting Maven build"
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - echo "Maven build completed"
artifacts:
  files:
    - target/myapp.war
